name: Node.js CI

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: login to docker hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $username -p $password 
      - name: create docker builder
        run: |
          docker buildx create --use --name mybuilder
      - name: build the docker image and push
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 . -f Dockerfile -t ${{secrets.DOCKERHUB_USERNAME}}/leave-frontend:latest --push
            
          
    
